# Generated by Django 5.2.5 on 2025-08-18 10:58

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_test_end_date_checktest_checkquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktest',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 10, 56, 36, 202651, tzinfo=datetime.timezone.utc)),
        ),
    ]
